name: GHEncantar
main: me.ghenchants.Main
version: 1.1.3

commands:
  addexp:
    aliases: [addxp]
  setexp:
    aliases: [setxp]
  encantar:
    aliases: [enchant]
  ghencantar:
    aliases: [ghenchant]
